name: Base CCCL workflow

on:
  workflow_call:
    inputs:
      matrix:
        type: string
        required: true

jobs:
  build:
    if: github.repository == 'NVIDIA/cccl'
    name: Build (CUDA ${{matrix.cuda}}, ${{ matrix.compiler.name }}-${{ matrix.compiler.version }}, C++-${{matrix.std}}, CPU ${{matrix.cpu}})
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix: ${{ fromJSON(inputs.matrix) }}
    runs-on: linux-${{ matrix.cpu }}-cpu16
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-${{matrix.compiler.name}}${{matrix.compiler.version}}-cuda${{matrix.cuda}}-ubuntu${{ matrix.ubuntu }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: test
        run: echo "hello"
