name: Base CCCL workflow

on:
  workflow_call:
    inputs:
      matrix: # The matrix to use for this job
        type: string
        required: true
      build_script: # The script to run for the build step
        type: string
        required: true
      test_script: 
        type: string
        required: true

jobs:
  build:
    if: github.repository == 'NVIDIA/cccl'
    name: Build/CUDA ${{matrix.cuda}}/${{ matrix.compiler.name }}${{ matrix.compiler.version }}/C++${{matrix.std}}/${{matrix.cpu}}
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix: ${{ fromJSON(inputs.matrix) }}
    runs-on: linux-${{ matrix.cpu }}-cpu16
    container: # Fetch the container image to use for the job
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-${{matrix.compiler.name}}${{matrix.compiler.version}}-cuda${{matrix.cuda}}-ubuntu${{ matrix.ubuntu }}
    permissions: # Set permissions needed for sccache/AWS credentials
      id-token: write
      contents: read
    steps:
    - name: Get AWS credentials for sccache bucket
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::279114543810:role/gha-oidc-NVIDIA
        aws-region: us-east-2 
        role-duration-seconds: 43200 # 12 hours
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run build script
      env: # Set environment variables for sccache
          SCCACHE_BUCKET: rapids-sccache-east
          SCCACHE_REGION: us-east-2
          SCCACHE_IDLE_TIMEOUT: 32768
          SCCACHE_S3_USE_SSL: true
          SCCACHE_S3_NO_CREDENTIALS: false
      run: |
        chmod +x ${{ inputs.build_script }}
        ./${{ inputs.build_script }}
        sccache -s
  test:
    needs: build
    if: github.repository == 'NVIDIA/cccl'
    name: Test/CUDA ${{matrix.cuda}}/${{ matrix.compiler.name }}${{ matrix.compiler.version }}/C++${{matrix.std}}/${{matrix.cpu}})
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix: ${{ fromJSON(inputs.matrix) }}
    runs-on: linux-${{matrix.cpu}}-gpu-v100-latest-1
    container: # Fetch the container image to use for the job
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-${{matrix.compiler.name}}${{matrix.compiler.version}}-cuda${{matrix.cuda}}-ubuntu${{ matrix.ubuntu }}
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    permissions: # Set permissions needed for sccache/AWS credentials
      id-token: write
      contents: read
    steps:
    - name: Get AWS credentials for sccache bucket
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::279114543810:role/gha-oidc-NVIDIA
        aws-region: us-east-2 
        role-duration-seconds: 43200 # 12 hours
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run test script
      env: # Set environment variables for sccache
          SCCACHE_BUCKET: rapids-sccache-east
          SCCACHE_REGION: us-east-2
          SCCACHE_IDLE_TIMEOUT: 32768
          SCCACHE_S3_USE_SSL: true
          SCCACHE_S3_NO_CREDENTIALS: false
      run: |
        chmod +x ${{ inputs.test_script }}
        ./${{ inputs.test_script }}
        sccache -s
