name: build and test

on:
  workflow_call:
    inputs:
      cuda_version: {type: string, required: true}
      compiler: {type: string, required: true}
      compiler_version: {type: string, required: true}
      std: {type: string, required: true}
      gpu_build_archs: {type: string, required: true}
      cpu: {type: string, required: true}
      build_script: {type: string, required: false}
      test_script: {type: string, required: false }

jobs:
  build:
    name: Build ${{inputs.compiler}}${{inputs.compiler_version}}/C++ ${{inputs.std}}/${{inputs.cpu}}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: | 
          "echo test"
  test:
    needs: build
    name: Test ${{inputs.compiler}}${{inputs.compiler_version}}/C++ ${{inputs.std}}/${{inputs.cpu}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: | 
          "echo test"
