name: build and test

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      cuda_version: {type: string, required: true}
      compiler: {type: string, required: true}
      compiler_version: {type: string, required: true}
      std: {type: string, required: true}
      gpu_build_archs: {type: string, required: true}
      cpu: {type: string, required: true}
      build_script: {type: string, required: false}
      test_script: {type: string, required: false }

jobs:
  build:
    if: inputs.build_script != ''
    name: Build ${{inputs.compiler}}${{inputs.compiler_version}}/C++${{inputs.std}}
    runs-on: ubuntu-latest
    #runs-on: linux-${{inputs.cpu}}-cpu16
    #container: # Fetch the container image to use for the job
    #  options: -u root
    #  image: rapidsai/devcontainers:23.06-cpp-${{matrix.compiler.name}}${{matrix.compiler.version}}-cuda${{matrix.cuda}}-ubuntu${{ matrix.ubuntu }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: repo
          submodules: 'recursive'
          fetch-depth: 0
          persist-credentials: false
      - name: pwd
        run: |
          pwd
          ls
          ls repo
      - name: Configure credentials and environment variables for sccache
        uses: ./repo/.github/actions/configure_cccl_sccache
      - name: Run build script
        run: | 
            time ./${{ inputs.build_script }}
  test:
    needs: build
    if:  ${{ !cancelled() && ( needs.build.result == 'success' || needs.build.result == 'skipped' ) && inputs.test_script != '' }}
    name: Test ${{inputs.compiler}}${{inputs.compiler_version}}/C++${{inputs.std}}
    runs-on: ubuntu-latest
    #runs-on: linux-${{inputs.cpu}}-gpu-v100-latest-1
    #container: # Fetch the container image to use for the job
    #  options: -u root
    #  image: rapidsai/devcontainers:23.06-cpp-${{matrix.compiler.name}}${{matrix.compiler.version}}-cuda${{matrix.cuda}}-ubuntu${{ matrix.ubuntu }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Configure credentials and environment variables for sccache
        uses: ./.github/actions/configure_cccl_sccache
      - name: Run test script
        run: | 
            time ./${{ inputs.test_script }}
