name: build and test

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      cuda_version: {type: string, required: true}
      compiler: {type: string, required: true}
      compiler_version: {type: string, required: true}
      std: {type: string, required: true}
      gpu_build_archs: {type: string, required: true}
      cpu: {type: string, required: true}
      build_script: {type: string, required: false}
      test_script: {type: string, required: false }

jobs:
  build:
    name: Build ${{inputs.compiler}}${{inputs.compiler_version}}/C++${{inputs.std}}/${{inputs.cpu}}
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: | 
          echo "test"
          if [[ -n "${{ inputs.build_script }}" ]]; then
            ./${{ inputs.build_script }}
          else
            echo "No build script provided, skipping."
          fi
  test:
    needs: build
    name: Test ${{inputs.compiler}}${{inputs.compiler_version}}/C++${{inputs.std}}/${{inputs.cpu}}
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Run test script
        run: | 
          echo "test"
          if [[ -n "${{ inputs.test_script }}" ]]; then
            ./${{ inputs.test_script }}
          else
            echo "No test script provided, skipping."
          fi
