name: Per compiler

on:
  workflow_call:
    inputs:
      cuda_version: {type: string, required: true}
      full_matrix: {type: string, required: true}
      compiler_name: {type: string, required: true}

jobs:
  per_compiler:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "CUDA: ${{inputs.cuda_version}} Compiler: ${{ inputs.compiler_name }}"


