name: Per CUDA version

on:
  workflow_call:
    inputs:
      per_cuda_matrix: {type: string, required: true}


jobs:
  per_cuda:
    runs-on: ubuntu-latest
        strategy:
      matrix: ${{ fromJSON(inputs.per_cuda_matrix) }}
    steps:
      - name: test
        run: |
          echo "per_cuda_matrix: ${{ inputs.per_cuda_matrix }}"


