name: Per compiler

on:
  workflow_call:
    inputs:
      cuda_version: {type: string, required: true}
      full_matrix: {type: string, required: true}
      compiler_name: {type: string, required: true}

jobs:

  compute_per_compiler_matrix:
    name: Compute ${{inputs.compiler_name}} matrix  
    runs-on: ubuntu-latest
    outputs:
      PER_COMPILER_MATRIX:  ${{ steps.compute_per_compiler_matrix.outputs.PER_COMPILER_MATRIX }}
    steps:
      - name: Compute Matrix
        id: compute_per_compiler_matrix
        run: |
          FULL_MATRIX="${{ toJSON(inputs.full_matrix) }}"
          TEST=echo "$FULL_MATRIX" | jq -c .
          echo "$TEST"

        #PER_COMPILER_MATRIX=$(echo $FULL_MATRIX | jq -c '[.[] | select(.compiler.name == "${{ inputs.compiler_name }}" and .cuda == "${{ inputs.cuda_version }}")]')
        #echo "PER_COMPILER_MATRIX=$PER_COMPILER_MATRIX" | tee -a "$GITHUB_OUTPUT"

  per_compiler:
    name: ${{ inputs.compiler_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJSON(needs.compute_per_compiler_matrix.outputs.PER_COMPILER_MATRIX) }}
    steps:
      - name: test
        run: |
          echo "CUDA: ${{matrix.cuda_version}} Compiler: ${{ matrix.compiler.name }} ${{ matrix.compiler.version }}"


