name: Per CUDA version

on:
  workflow_call:
    inputs:
      per_cuda_compiler_matrix: {type: string, required: true}

jobs:
  build_and_test:
    uses: ./.github/workflows/build-and-test.yml
    strategy:
      matrix: 
        include: ${{ fromJSON(inputs.per_cuda_compiler_matrix) }}
    with:
      cuda_version: "11.0"
      compiler: "gcc"
      compiler_version: "7"
      std: "11"
      cpu: "amd64"
      gpu_build_archs: "70;75;80"

  #build:
  #  name: Build ${{ matrix.compiler.name }}${{ matrix.compiler.version }}/C++ ${{matrix.std}}/${{matrix.cpu}}
  #  strategy:
  #    matrix: 
  #      include: ${{ fromJSON(inputs.per_cuda_compiler_matrix) }}
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: test
  #      run: |
  #        echo "CUDA: ${{ matrix.cuda_version }} Compiler: ${{ matrix.compiler }} ${{ matrix.compiler_version }}"
  #test:
  #  needs: build
  #  name: Test ${{ matrix.compiler.name }}${{ matrix.compiler.version }}/C++ ${{matrix.std}}/${{matrix.cpu}}
  #  strategy:
  #    matrix: 
  #      include: ${{ fromJSON(inputs.per_cuda_compiler_matrix) }}
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: test
  #      run: |
  #        echo "CUDA: ${{ matrix.cuda_version }} Compiler: ${{ matrix.compiler }} ${{ matrix.compiler_version }}"


