
# This is the main workflow that runs on every PR and push to main
name: pr

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"

# Only runs one instance of this workflow at a time for a given PR and cancels any in-progress runs when a new one starts.
concurrency:
  group: ${{ github.workflow }}-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  linux-build-test:
    name: Linux
    uses: ./.github/workflows/linux-build-and-test.yml
    with:
      matrix_file: ./ci/matrix.yaml
      build_type: "pull-request"

