name: CI (GPU)

env:
  DEVCONTAINER_VERSION: '23.06'

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'NVIDIA/cccl'
    name: Build (CUDA ${{matrix.cuda}}, ${{ matrix.compiler.name }}-${{ matrix.compiler.version }}, Ubuntu ${{ matrix.ubuntu }}, CPU ${{matrix.cpu}})
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        include:
          # gcc
          #- {cuda: '11.0', ubuntu: '18.04', cpu: 'amd64', compiler: 'gcc7'}
          #- {cuda: '11.0', ubuntu: '18.04', cpu: 'amd64', compiler: 'gcc8'}
          #- {cuda: '11.0', ubuntu: '18.04', cpu: 'amd64', compiler: 'gcc9'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'gcc7'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'gcc8'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'gcc9'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'gcc10'}
          #- {cuda: '12.1', ubuntu: '22.04', cpu: 'amd64', compiler: 'gcc11'}
          - {cuda: '12.1', ubuntu: '22.04', cpu: 'amd64', compiler: {name: 'gcc', version: '12'}}
          # clang
          #- {cuda: '11.0', ubuntu: '18.04', cpu: 'amd64', compiler: 'llvm9'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm9'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm10'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm11'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm12'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm13'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm14'}
          #- {cuda: '12.1', ubuntu: '22.04', cpu: 'amd64', compiler: 'llvm15'}
          #- {cuda: '12.1', ubuntu: '22.04', cpu: 'amd64', compiler: 'llvm16'}
    runs-on: linux-${{ matrix.cpu }}-cpu16
    container:
      options: -u root
      image: rapidsai/devcontainers:${{env.DEVCONTAINTER_VERSION}}-cpp-${{matrix.compiler.name}}${{matrix.compiler.version}}-cuda${{matrix.cuda}}-ubuntu${{ matrix.ubuntu }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build Thrust tests
        run: bash ./ci/build_thrust.sh
      - name: Upload Thrust build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: thrust-build-artifacts
          path: ./thrust/
  test:
    name: Run tests
    needs: build
    runs-on: linux-amd64-gpu-v100-latest-1
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-gcc12-cuda12.1-ubuntu22.04
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
      - name: Download Thrust build artifacts
        uses: actions/download-artifact@v3
        with:
          name: thrust-build-artifacts
          path: thrust
      - name: Run Thrust tests
        run: pwd && ls && ctest --test-dir thrust/build --output-on-failure