name: CI (GPU)

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'NVIDIA/cccl'
    name: Build (CUDA ${{matrix.cuda}}, ${{ matrix.compiler }}, Ubuntu ${{ matrix.ubuntu }}, CPU ${{matrix.cpu}})
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        include:
          # gcc
          #- {cuda: '11.0', ubuntu: '18.04', cpu: 'amd64', compiler: 'gcc7'}
          #- {cuda: '11.0', ubuntu: '18.04', cpu: 'amd64', compiler: 'gcc8'}
          #- {cuda: '11.0', ubuntu: '18.04', cpu: 'amd64', compiler: 'gcc9'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'gcc7'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'gcc8'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'gcc9'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'gcc10'}
          #- {cuda: '12.1', ubuntu: '22.04', cpu: 'amd64', compiler: 'gcc11'}
          - {cuda: '12.1', ubuntu: '22.04', cpu: 'amd64', compiler: 'gcc12'}
          # clang
          #- {cuda: '11.0', ubuntu: '18.04', cpu: 'amd64', compiler: 'llvm9'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm9'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm10'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm11'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm12'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm13'}
          #- {cuda: '12.1', ubuntu: '20.04', cpu: 'amd64', compiler: 'llvm14'}
          #- {cuda: '12.1', ubuntu: '22.04', cpu: 'amd64', compiler: 'llvm15'}
          #- {cuda: '12.1', ubuntu: '22.04', cpu: 'amd64', compiler: 'llvm16'}
    runs-on: linux-${{ matrix.cpu }}-cpu4
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-${{ matrix.compiler }}-cuda${{matrix.cuda}}-ubuntu${{ matrix.ubuntu }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print working dir
        run: pwd
      - name: list
        run: ls
      - name: Build Thrust tests
        run: ./ci/build_thrust.sh