name: CI (GPU)

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'NVIDIA/cccl'
    name: Build (CUDA ${{matrix.cuda}}, ${{ matrix.compiler }}, Ubuntu ${{ matrix.ubuntu }}, CPU ${{matrix.cpu}})
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        include:
          - cuda: '12.1' ubuntu: '20.04' cpu: 'amd64' compiler: ['gcc7', 'gcc8', 'gcc9', 'gcc10', 'llvm9', 'llvm10', 'llvm11', 'llvm12', 'llvm13', 'llvm14']
          - cuda: '12.1' ubuntu: '22.04' cpu: 'amd64' compiler: ['gcc11', 'gcc12', 'llvm15', 'llvm16']
          - cuda: '11.0' ubuntu: '18.04' cpu: 'amd64' compiler: ['gcc7', 'gcc8', 'gcc9', 'llvm9']
    runs-on: linux-${{ matrix.cpu }}-cpu4
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-${{ matrix.compiler }}-cuda12.1-ubuntu${{ matrix.ubuntu }}
    steps:
      - name: Echo matrix
        run: echo "${{matrix.compiler}}"