name: CI (GPU)

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  cuda12_1:
    if: github.repository == 'NVIDIA/cccl'
    name: Build (CUDA 12.1, ${{ matrix.compiler }}, Ubuntu ${{ matrix.ubuntu }})
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        compiler: [gcc7, gcc8, gcc9, gcc10, clang9, clang10, clang11, clang12, clang13, clang14]
        ubuntu: ["20.04"]
        #cxx: [11, 14, 17]
        #cpu: [amd64, arm64] 
    #runs-on: linux-${{ matrix.cpu }}-cpu4
    runs-on: linux-amd64-cpu4
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-${{ matrix.compiler }}-cuda12.1-ubuntu${{ matrix.ubuntu }}
    steps:
      - name: Echo matrix
        run: echo "${{matrix.compiler}}"
  cuda11_0:
    if: github.repository == 'NVIDIA/cccl'
    name: Build (CUDA 11.0, ${{matrix.compiler}}, Ubuntu ${{ matrix.ubuntu }})
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        compiler: [gcc7, gcc8, gcc9, clang9]
        ubuntu: ["18.04"]
        #cxx: [11, 14, 17]
        #cpu: [amd64, arm64] 
    #runs-on: linux-${{ matrix.cpu }}-cpu4
    runs-on: linux-amd64-cpu4
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-${{matrix.compiler}}-cuda11.0-ubuntu${{ matrix.ubuntu }}
    steps:
      - name: Echo matrix
        run: echo "${{matrix.compiler}}"