name: CI (GPU)

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'NVIDIA/cccl'
    name: Build (${{ matrix.cpu }}, gcc ${{ matrix.gcc }}, C++${{ matrix.cxx }}, CUDA ${{ matrix.ctk }})
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        gcc: [7, 8, 9, 10]
        ctk: ["11.0", "12.1"]
        cxx: [11, 14, 17]
        #cpu: [amd64, arm64] 
    #runs-on: linux-${{ matrix.cpu }}-cpu4
    runs-on: linux-amd64-cpu4
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-gcc${{ matrix.gcc }}-cuda${{ matrix.ctk }}-ubuntu20.04
    steps:
      - name: Echo matrix
        run: echo ${{ matrix.gcc }}, ${{matrix.ctk}}, ${{matrix.cxx}}, ${{matrix.cpu}}